require Rails.root.join('spec', 'spec_helper.rb')


truncate_all_tables


# insert Language
lang = Language.gen(:code => 'en', :name => 'english')

# Insert some blank records in books to start downloading metadata from DAR
Book.gen(:bibid => 'DAF-BHL:popularsciencemo31newy', :language => lang)
Book.gen(:bibid => 'DAF-BHL:proceedingsofbio14biol', :language => lang)
Book.gen(:bibid => 'DAF-BHL:plantsxrays00bres', :language => lang)
Book.gen(:bibid => 'DAF-BHL:proceedingsofamep59amer', :language => lang)
Book.gen(:bibid => 'DAF-BHL:pamphfores01montrich', :language => lang)
Book.gen(:bibid => 'DAF-BHL:proceedingsofamep50150amer', :language => lang)
Book.gen(:bibid => 'DAF-BHL:popularsciencemo48newy', :language => lang)
Book.gen(:bibid => 'DAF-BHL:postilla601962peab', :language => lang)
Book.gen(:bibid => 'DAF-BHL:proceedingsofuni561920unit', :language => lang)
Book.gen(:bibid => 'DAF-BHL:proceedingsofamep27amer', :language => lang)
Book.gen(:bibid => 'DAF-BHL:pnreports07canauoft', :language => lang)
Book.gen(:bibid => 'DAF-BHL:proceedingsofsec221koni', :language => lang)
Book.gen(:bibid => 'DAF-BHL:phytologia835glea', :language => lang)
Book.gen(:bibid => 'DAF-BHL:provisionallisto00cock', :language => lang)
Book.gen(:bibid => 'DAF-BHL:proceedingsofroy3321roya', :language => lang)
Book.gen(:bibid => 'DAF-BHL:popularsciencemo72newy', :language => lang)
Book.gen(:bibid => 'DAF-BHL:postilla112peab', :language => lang)
Book.gen(:bibid => 'DAF-BHL:popularsciencemon64newy', :language => lang)
Book.gen(:bibid => 'DAF-BHL:principlesofecon01daug', :language => lang)
Book.gen(:bibid => 'DAF-BHL:proceedingsofroy27roya', :language => lang)
Book.gen(:bibid => 'DAF-BHL:ptycholepismarsh3312scha', :language => lang)
Book.gen(:bibid => 'DAF-BHL:practicalfloricu00hend', :language => lang)
Book.gen(:bibid => 'DAF-BHL:proceedingsofame1898amer', :language => lang)
Book.gen(:bibid => 'DAF-BHL:plantsman1110newh', :language => lang)
Book.gen(:bibid => 'DAF-BHL:practicalguideto00rexf', :language => lang)
Book.gen(:bibid => 'DAF-BHL:plantspoisonoust00long', :language => lang)
Book.gen(:bibid => 'DAF-BHL:plantlife1913farm', :language => lang)
Book.gen(:bibid => 'DAF-BHL:p2generalzoology12shawuoft', :language => lang)
Book.gen(:bibid => 'DAF-BHL:plantculturework02oliv', :language => lang)
Book.gen(:bibid => 'DAF-BHL:presidentialaddr00arnouoft', :language => lang)
Book.gen(:bibid => 'DAF-BHL:papersfromhopkin16hopkrich', :language => lang)
Book.gen(:bibid => 'DAF-BHL:proceedingsofwas01wash', :language => lang)
Book.gen(:bibid => 'DAF-BHL:postilla721962peab', :language => lang)
Book.gen(:bibid => 'DAF-BHL:popularsciencemo21newyuoft', :language => lang)
Book.gen(:bibid => 'DAF-BHL:popularcalifornaf00ratt', :language => lang)
Book.gen(:bibid => 'DAF-BHL:pamphletsonlumbe01lumbrich', :language => lang)
Book.gen(:bibid => 'DAF-BHL:pt2repor08prinuoft', :language => lang)
Book.gen(:bibid => 'DAF-BHL:proceedingsofbat07bath', :language => lang)
Book.gen(:bibid => 'DAF-BHL:primaevalworldof02heerrich', :language => lang)
Book.gen(:bibid => 'DAF-BHL:phytologia646glea', :language => lang)
Book.gen(:bibid => 'DAF-BHL:phytologia791glea', :language => lang)
Book.gen(:bibid => 'DAF-BHL:proceedingsofame37amer', :language => lang)
Book.gen(:bibid => 'DAF-BHL:proceedingsofaca1912acad', :language => lang)
Book.gen(:bibid => 'DAF-BHL:popularsciencemo23newyuoft', :language => lang)
Book.gen(:bibid => 'DAF-BHL:popularsciencemo15newy', :language => lang)
Book.gen(:bibid => 'DAF-BHL:philosophicalmag36lond', :language => lang)
Book.gen(:bibid => 'DAF-BHL:proceedingsofaca19acad', :language => lang)
Book.gen(:bibid => 'DAF-BHL:proceedingsofaca6820acad', :language => lang)
Book.gen(:bibid => 'DAF-BHL:proceedingsofsou191517sout', :language => lang)
Book.gen(:bibid => 'DAF-BHL:phytologia826glea', :language => lang)
Book.gen(:bibid => 'DAF-BHL:protectionofwood00fruoft', :language => lang)
Book.gen(:bibid => 'DAF-BHL:p1internationachem1904royauoft', :language => lang)
Book.gen(:bibid => 'DAF-BHL:proceedingsofsec62koni', :language => lang)
Book.gen(:bibid => 'DAF-BHL:phytologia696glea', :language => lang)
Book.gen(:bibid => 'DAF-BHL:phytologia60glea', :language => lang)
Book.gen(:bibid => 'DAF-BHL:principlesofscie00jevorich', :language => lang)
Book.gen(:bibid => 'DAF-BHL:proceedingstrans27roya', :language => lang)
Book.gen(:bibid => 'DAF-BHL:phytologia04glea', :language => lang)
Book.gen(:bibid => 'DAF-BHL:popularsciencemo09newyuoft', :language => lang)
Book.gen(:bibid => 'DAF-BHL:phytologia621glea', :language => lang)
Book.gen(:bibid => 'DAF-BHL:proceedingstrans68386nova', :language => lang)
Book.gen(:bibid => 'DAF-BHL:proceedingsofcal0415cali', :language => lang)
Book.gen(:bibid => 'DAF-BHL:pacificcoastavif04coop', :language => lang)
Book.gen(:bibid => 'DAF-BHL:proceedingsofuni1181967unit', :language => lang)
Book.gen(:bibid => 'DAF-BHL:plantsman92121newh', :language => lang)
Book.gen(:bibid => 'DAF-BHL:postilla621962peab', :language => lang)
Book.gen(:bibid => 'DAF-BHL:popularsciencemo23newy', :language => lang)
Book.gen(:bibid => 'DAF-BHL:practicaltreatis01alle', :language => lang)
Book.gen(:bibid => 'DAF-BHL:pennsylvaniawild00shoe', :language => lang)
Book.gen(:bibid => 'DAF-BHL:popularsciencemo11newy', :language => lang)
Book.gen(:bibid => 'DAF-BHL:proceedingsofnat65nati', :language => lang)
Book.gen(:bibid => 'DAF-BHL:proceedingsofroy30roya', :language => lang)
Book.gen(:bibid => 'DAF-BHL:prizeportableagr00clay', :language => lang)
Book.gen(:bibid => 'DAF-BHL:plantgeographyup00schi', :language => lang)
Book.gen(:bibid => 'DAF-BHL:pterodesmidmilli622hoff', :language => lang)
Book.gen(:bibid => 'DAF-BHL:proceedingsofasi92asia', :language => lang)
Book.gen(:bibid => 'DAF-BHL:popularsciencemo41newy', :language => lang)
Book.gen(:bibid => 'DAF-BHL:peculiarbearfrom101osgo', :language => lang)
Book.gen(:bibid => 'DAF-BHL:postilla107peab', :language => lang)
Book.gen(:bibid => 'DAF-BHL:pacificcoastavif02coop', :language => lang)
Book.gen(:bibid => 'DAF-BHL:personalityofpla00dixo', :language => lang)
Book.gen(:bibid => 'DAF-BHL:proceedingsofaca74acad', :language => lang)
Book.gen(:bibid => 'DAF-BHL:pomonajournalofe12190910pomon', :language => lang)
Book.gen(:bibid => 'DAF-BHL:proceedingsofroy1518roya', :language => lang)
Book.gen(:bibid => 'DAF-BHL:phytologia686glea', :language => lang)
Book.gen(:bibid => 'DAF-BHL:presentcondition00wash', :language => lang)
Book.gen(:bibid => 'DAF-BHL:popularsciencemo571900newy', :language => lang)
Book.gen(:bibid => 'DAF-BHL:plantsman1995newh', :language => lang)
Book.gen(:bibid => 'DAF-BHL:postilla133peab', :language => lang)
Book.gen(:bibid => 'DAF-BHL:proceedingsofame51amer', :language => lang)
Book.gen(:bibid => 'DAF-BHL:proceedingsofuni601922unit', :language => lang)
Book.gen(:bibid => 'DAF-BHL:principlesofprof00germrich', :language => lang)
Book.gen(:bibid => 'DAF-BHL:proceedingsofame08amer', :language => lang)
Book.gen(:bibid => 'DAF-BHL:proceedingsoflin27linn', :language => lang)
Book.gen(:bibid => 'DAF-BHL:postilla961966peab', :language => lang)
Book.gen(:bibid => 'DAF-BHL:polychlorinatedb00eisl', :language => lang)
Book.gen(:bibid => 'DAF-BHL:proceedingsofsec231koni', :language => lang)
Book.gen(:bibid => 'DAF-BHL:proceedingsofbat01bath', :language => lang)
Book.gen(:bibid => 'DAF-BHL:proceedingsofroy01lond', :language => lang)
Book.gen(:bibid => 'DAF-BHL:phytologia845glea', :language => lang)

